language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

sudo: required # Linux administrator permissions

before_install:
  - sudo apt update # Update the package list

install:
  - sudo apt install maven -y # Install required packages

script: 
  - mvn clean package jacoco:report cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t bffea5bd-7caa-4f7a-b0bf-bfcc4086577c
  - java -jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/main/resources/TestClass.java regex local actual_metrics csv
  - echo "loc,noc,nom," > expected_metrics.csv
  - echo "21,3,3," >> expected_metrics.csv
  - if [ !(cmp --silent actual_metrics.csv expected_metrics.csv) ]; then 
    echo "WARNING: Integration test fail!";
    exit 1;
    fi
  - echo "SUCCESS: Integration test pass!"

