language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

sudo: required # Linux administrator permissions

before_install:
  - sudo apt update # Update the package list

install:
  - sudo apt install maven -y # Install required packages

script: 
  - mvn clean package jacoco:report

after_success:
  - echo "Process terminated successfully"


